# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ee76c6cf153b27d6193241badeeecfe6977073e6c30b5cb131f5a54c51e7be6b8b17567cce527f1e387d2c96508b4e5e95b5c9c8154729d8991aaaeec0d8855

test:
  secret_key_base: 23dc5d7d7ad9d5c3e8a0203dbfa0e43d84fc727ff96d123814066bafc576362ce3c387a29b2aa93bfd8730332e713e03625966b44fb5e51b3273ac07585e089e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
